modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="curse"
version="1.3.1"
displayName="Curse"
credits="Jusey1"
displayURL="https://discord.gg/s7QaYGUzZU"
authors="Jusey1"

[[dependencies.curse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




