modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="curse"
version="1.2.0"
displayName="Curse"
credits="Jusey1"
displayURL="https://discord.gg/s7QaYGUzZU"
authors="Jusey1"

[[dependencies.curse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




